export interface AmenitySeed {
  id: string;
  code: string;
  name: string;
  description: string | undefined;
  icon: string;
  is_predefined: boolean;
  is_active: boolean;
}

const PREFIX = "amen";

export const AMENITY_SEEDS: AmenitySeed[] = [
  // ===== ESTACIONAMENTO & ACESSO =====
  {
    id: `${PREFIX}_01KCABRCZAV7ZXXCAZKQ5E8BJ2`,
    code: 'estacionamento_gratuito',
    name: 'Estacionamento Gratuito',
    description: 'Vagas de estacionamento sem custo para clientes',
    icon: '🅿️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAQBGGFH2M0FM6HBTK`,
    code: 'estacionamento_conveniado',
    name: 'Estacionamento Conveniado',
    description: 'Estacionamento com desconto para clientes',
    icon: '🚗',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAA0DGHJ6EA074YV8Q`,
    code: 'valet',
    name: 'Serviço de Valet',
    description: 'Manobrista disponível para estacionar seu veículo',
    icon: '🔑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAM2Y32KN66NYJRQA9`,
    code: 'acesso_cadeirante',
    name: 'Acessibilidade para Cadeirantes',
    description: 'Rampas e estrutura adaptada para cadeirantes',
    icon: '♿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAZ7SNY24CXQH6GNG2`,
    code: 'elevador',
    name: 'Elevador',
    description: 'Elevador disponível no estabelecimento',
    icon: '🛗',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA094HT5J65671J4YJ`,
    code: 'entrada_independente',
    name: 'Entrada Independente',
    description: 'Entrada privativa e discreta',
    icon: '🚪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA6ZQ49JZPY0Q6KDEY`,
    code: 'proximo_metro',
    name: 'Próximo ao Metrô',
    description: 'Localização próxima a estação de metrô',
    icon: '🚇',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA7AXWRVG96ZEN4D60`,
    code: 'proximo_ponto_onibus',
    name: 'Próximo a Ponto de Ônibus',
    description: 'Localização próxima a ponto de ônibus',
    icon: '🚌',
    is_predefined: true,
    is_active: true,
  },

  // ===== CONFORTO & ESPERA =====
  {
    id: `${PREFIX}_01KCABRCZAZ0ZSJ0TN41FCXX3J`,
    code: 'wifi_gratuito',
    name: 'Wi-Fi Gratuito',
    description: 'Internet sem fio disponível para clientes',
    icon: '📶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA31ZRQC37EK6EYWQB`,
    code: 'ar_condicionado',
    name: 'Ar-condicionado',
    description: 'Ambiente climatizado',
    icon: '❄️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA22N9ZAC9QQTC4VCD`,
    code: 'recepcao_confortavel',
    name: 'Recepção Confortável',
    description: 'Área de espera aconchegante com poltronas',
    icon: '🛋️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAZ855RNCCQPTKT8CD`,
    code: 'tv',
    name: 'TV na Recepção',
    description: 'Televisão disponível na área de espera',
    icon: '📺',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAS8AGR386P6HNSB9Z`,
    code: 'revistas_atualizadas',
    name: 'Revistas Atualizadas',
    description: 'Revistas e publicações recentes para leitura',
    icon: '📰',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAKHQVA2G2P37MJE06`,
    code: 'musica_ambiente',
    name: 'Música Ambiente',
    description: 'Som ambiente agradável',
    icon: '🎵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZAW3C65FDMADW0J4K4`,
    code: 'aromaterapia_ambiente',
    name: 'Aromaterapia no Ambiente',
    description: 'Difusores com óleos essenciais',
    icon: '🌸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZA4900QA8NYDP76PSM`,
    code: 'ambiente_silencioso',
    name: 'Ambiente Silencioso',
    description: 'Espaço tranquilo e silencioso',
    icon: '🤫',
    is_predefined: true,
    is_active: true,
  },

  // ===== BEBIDAS & ALIMENTAÇÃO =====
  {
    id: `${PREFIX}_01KCABRCZAA2SZGNBTJBTVCB1R`,
    code: 'cafe_cortesia',
    name: 'Café de Cortesia',
    description: 'Café disponível gratuitamente',
    icon: '☕',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBBDG65W34FZNWPDGV`,
    code: 'agua_cortesia',
    name: 'Água de Cortesia',
    description: 'Água mineral disponível gratuitamente',
    icon: '💧',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB12P58G1FVPNWGZH6`,
    code: 'cha_cortesia',
    name: 'Chá de Cortesia',
    description: 'Variedade de chás disponíveis',
    icon: '🍵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBAHXERS48YTX4S6TD`,
    code: 'suco_natural',
    name: 'Suco Natural',
    description: 'Sucos naturais disponíveis',
    icon: '🥤',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB7H41HCGM2RVXYBNF`,
    code: 'champagne',
    name: 'Champagne/Espumante',
    description: 'Champagne ou espumante de cortesia',
    icon: '🥂',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBAR1V8XR6GV4578HW`,
    code: 'snacks',
    name: 'Snacks/Petiscos',
    description: 'Lanches leves disponíveis',
    icon: '🍪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBD4K045EE5QZ84EVD`,
    code: 'frutas_frescas',
    name: 'Frutas Frescas',
    description: 'Frutas frescas de cortesia',
    icon: '🍇',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBTQ1CW3P8V7VWG3JS`,
    code: 'bar_bebidas',
    name: 'Bar de Bebidas',
    description: 'Bar completo com diversas opções',
    icon: '🍹',
    is_predefined: true,
    is_active: true,
  },

  // ===== PAGAMENTO & FACILIDADES =====
  {
    id: `${PREFIX}_01KCABRCZBSFD9A5MCZCAGE80P`,
    code: 'cartao_credito',
    name: 'Aceita Cartão de Crédito',
    description: 'Pagamento em cartão de crédito disponível',
    icon: '💳',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBM8XW8858N0CQ6A22`,
    code: 'cartao_debito',
    name: 'Aceita Cartão de Débito',
    description: 'Pagamento em cartão de débito disponível',
    icon: '💳',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBG4NE81JCAEQV1G22`,
    code: 'pix',
    name: 'Aceita PIX',
    description: 'Pagamento via PIX disponível',
    icon: '📱',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBRWNJR42ZFMWTVPFE`,
    code: 'parcelamento',
    name: 'Parcelamento',
    description: 'Opção de parcelamento disponível',
    icon: '🔄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBF9WA8CJ8NEVJDVBK`,
    code: 'vale_presente',
    name: 'Vale-Presente',
    description: 'Gift cards disponíveis para presente',
    icon: '🎁',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBB3T52G0BX6EQHTZ0`,
    code: 'programa_fidelidade',
    name: 'Programa de Fidelidade',
    description: 'Acumule pontos e ganhe benefícios',
    icon: '⭐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB7T8E3489A72B2BT8`,
    code: 'pacotes_promocionais',
    name: 'Pacotes Promocionais',
    description: 'Pacotes com desconto disponíveis',
    icon: '🏷️',
    is_predefined: true,
    is_active: true,
  },

  // ===== ATENDIMENTO & SERVIÇO =====
  {
    id: `${PREFIX}_01KCABRCZBFMF8BCHY48A3ZJMN`,
    code: 'agendamento_online',
    name: 'Agendamento Online',
    description: 'Agende pelo site ou aplicativo',
    icon: '📅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB3QAN3DHRFEMGV6DQ`,
    code: 'atendimento_domiciliar',
    name: 'Atendimento Domiciliar',
    description: 'Serviço disponível em domicílio',
    icon: '🏠',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBM92RMA8SSD4ZZ90N`,
    code: 'atendimento_24h',
    name: 'Atendimento 24 Horas',
    description: 'Funcionamento ininterrupto',
    icon: '🕐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBEW7DG2D8WMSH573J`,
    code: 'horario_estendido',
    name: 'Horário Estendido',
    description: 'Funcionamento além do horário comercial',
    icon: '🌙',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBQSYXK601D9TNC0G0`,
    code: 'aberto_sabados',
    name: 'Aberto aos Sábados',
    description: 'Funcionamento aos sábados',
    icon: '📆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB9WZJHXWVYN1RZ29X`,
    code: 'aberto_domingos',
    name: 'Aberto aos Domingos',
    description: 'Funcionamento aos domingos',
    icon: '📆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBVDP1W7PAJJBWQM0Q`,
    code: 'aberto_feriados',
    name: 'Aberto em Feriados',
    description: 'Funcionamento em feriados',
    icon: '🎉',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB3HPBZ15CRDK8EM8N`,
    code: 'atendimento_emergencia',
    name: 'Atendimento de Emergência',
    description: 'Disponível para urgências',
    icon: '🚨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB5D1CFQ1PFKSMCX7R`,
    code: 'consulta_online',
    name: 'Consulta Online',
    description: 'Atendimento por videochamada',
    icon: '💻',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBQNT9H3RCGRYV0ZY7`,
    code: 'confirmacao_whatsapp',
    name: 'Confirmação por WhatsApp',
    description: 'Lembrete e confirmação via WhatsApp',
    icon: '📲',
    is_predefined: true,
    is_active: true,
  },

  // ===== SEGURANÇA & HIGIENE =====
  {
    id: `${PREFIX}_01KCABRCZB6P5WPNX05CAYFPAS`,
    code: 'material_esterilizado',
    name: 'Material Esterilizado',
    description: 'Todos materiais são esterilizados',
    icon: '🧼',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB1CP5M7TWKH7J8KHZ`,
    code: 'autoclave',
    name: 'Autoclave',
    description: 'Esterilização por autoclave',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZB3AVAFF0GCEM6TF0J`,
    code: 'material_descartavel',
    name: 'Material Descartável',
    description: 'Uso de materiais descartáveis',
    icon: '🗑️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBZQRXW4079WE75YNP`,
    code: 'alcool_gel',
    name: 'Álcool Gel Disponível',
    description: 'Álcool gel em todo o estabelecimento',
    icon: '🧴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBD7AWQ057TZEXEJ9F`,
    code: 'protocolo_higiene',
    name: 'Protocolo de Higiene Rigoroso',
    description: 'Seguimos todos protocolos de higiene',
    icon: '✅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZBRN52BQC8TCEB1WQX`,
    code: 'seguranca_24h',
    name: 'Segurança 24 Horas',
    description: 'Vigilância e segurança patrimonial',
    icon: '🔒',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCDJWHEHHS8FKTSS3K`,
    code: 'camera_seguranca',
    name: 'Câmeras de Segurança',
    description: 'Monitoramento por câmeras',
    icon: '📹',
    is_predefined: true,
    is_active: true,
  },

  // ===== CRIANÇAS & FAMÍLIA =====
  {
    id: `${PREFIX}_01KCABRCZCFJTHQBDNBMD9KBZE`,
    code: 'espaco_kids',
    name: 'Espaço Kids',
    description: 'Área de recreação para crianças',
    icon: '🧸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCPD9R6K1FETKCA2MF`,
    code: 'fraldario',
    name: 'Fraldário',
    description: 'Espaço para troca de fraldas',
    icon: '👶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCVSK2N715M1BWD59P`,
    code: 'atendimento_infantil',
    name: 'Atendimento Infantil',
    description: 'Especializado em atendimento de crianças',
    icon: '👧',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCXQV30K7NGMN1K0SQ`,
    code: 'carrinho_bebe',
    name: 'Acesso para Carrinho de Bebê',
    description: 'Espaço adaptado para carrinhos',
    icon: '🍼',
    is_predefined: true,
    is_active: true,
  },

  // ===== PETS =====
  {
    id: `${PREFIX}_01KCABRCZCSVNMBS8J5SPP4XWR`,
    code: 'pet_friendly',
    name: 'Pet Friendly',
    description: 'Animais de estimação são bem-vindos',
    icon: '🐕',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCHYA55Y82GAVS3P7M`,
    code: 'agua_pets',
    name: 'Água para Pets',
    description: 'Bebedouro disponível para pets',
    icon: '🐾',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTRUTURA & EQUIPAMENTOS =====
  {
    id: `${PREFIX}_01KCABRCZC6ZTVADZAYT3ZMAER`,
    code: 'salas_privativas',
    name: 'Salas Privativas',
    description: 'Salas individuais para maior privacidade',
    icon: '🚪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC6JSJD27967GV4QHE`,
    code: 'suite_vip',
    name: 'Suíte VIP',
    description: 'Espaço exclusivo para clientes VIP',
    icon: '👑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC2QA2FTS2RKF1K14K`,
    code: 'vestiario',
    name: 'Vestiário',
    description: 'Vestiário com armários',
    icon: '🚿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCEJF3RQ6QFSSW13QX`,
    code: 'chuveiro',
    name: 'Chuveiro',
    description: 'Chuveiro disponível para clientes',
    icon: '🚿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCWCPK337F10GXA2BJ`,
    code: 'banheiro_privativo',
    name: 'Banheiro Privativo',
    description: 'Banheiro exclusivo para clientes',
    icon: '🚻',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC32WT1MCHZ46VMZJH`,
    code: 'roupao',
    name: 'Roupão',
    description: 'Roupão disponível durante o atendimento',
    icon: '🥋',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC8AA930MDFP5DR0KX`,
    code: 'chinelo_descartavel',
    name: 'Chinelo Descartável',
    description: 'Chinelos descartáveis disponíveis',
    icon: '🩴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC9G1KN89TSCMEPNS4`,
    code: 'toalhas_macias',
    name: 'Toalhas Macias',
    description: 'Toalhas de alta qualidade',
    icon: '🛁',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC8Z2VD62SBG698WV9`,
    code: 'lencol_descartavel',
    name: 'Lençol Descartável',
    description: 'Lençóis descartáveis em macas',
    icon: '🛏️',
    is_predefined: true,
    is_active: true,
  },

  // ===== EQUIPAMENTOS ESPECIAIS =====
  {
    id: `${PREFIX}_01KCABRCZC0V5KZXRMXSTMNE7Q`,
    code: 'maca_eletrica',
    name: 'Maca Elétrica',
    description: 'Macas com ajuste elétrico',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCTC1RQJ2YMWZJ3HR3`,
    code: 'cadeira_massagem',
    name: 'Cadeira de Massagem',
    description: 'Cadeira de massagem na recepção',
    icon: '💆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC7D6DQ1JSBBBWKK4D`,
    code: 'equipamentos_modernos',
    name: 'Equipamentos Modernos',
    description: 'Tecnologia de última geração',
    icon: '🔧',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCZYSKJ3E8GT77H2ZJDZ`,
    code: 'produtos_profissionais',
    name: 'Produtos Profissionais',
    description: 'Uso de produtos de marcas renomadas',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCF9H0816TPB573MJX`,
    code: 'produtos_veganos',
    name: 'Produtos Veganos',
    description: 'Opções de produtos veganos e cruelty-free',
    icon: '🌱',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCA57F9Q5S3DX5T8XK`,
    code: 'produtos_organicos',
    name: 'Produtos Orgânicos',
    description: 'Produtos com ingredientes orgânicos',
    icon: '🍃',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCQA30SH4BS3R9RY0V`,
    code: 'produtos_hipoalergenicos',
    name: 'Produtos Hipoalergênicos',
    description: 'Opções para peles sensíveis',
    icon: '🧪',
    is_predefined: true,
    is_active: true,
  },

  // ===== BELEZA & ESTÉTICA =====
  {
    id: `${PREFIX}_01KCABRCZC2F80J7B6J562ES6E`,
    code: 'espelho_led',
    name: 'Espelhos com LED',
    description: 'Espelhos iluminados de alta qualidade',
    icon: '🪞',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCPRJ0PG08QKVTMRRF`,
    code: 'secador_profissional',
    name: 'Secadores Profissionais',
    description: 'Secadores de última geração',
    icon: '💨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCH6Y9614P4XCTQQV0`,
    code: 'lavatorio_massagem',
    name: 'Lavatório com Massagem',
    description: 'Lavatórios com massageador',
    icon: '🚿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCS7R90VDCFXCNZPTQ`,
    code: 'cabine_bronzeamento',
    name: 'Cabine de Bronzeamento',
    description: 'Cabine para bronzeamento artificial',
    icon: '☀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZCTF39VP37T396JX29`,
    code: 'sauna',
    name: 'Sauna',
    description: 'Sauna seca ou a vapor disponível',
    icon: '🧖',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZC93EYMXXPS3XRVQ2G`,
    code: 'ofuro',
    name: 'Ofurô',
    description: 'Banheira estilo japonês',
    icon: '🛁',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDDW9GEWC19FCM3TE2`,
    code: 'hidromassagem',
    name: 'Hidromassagem',
    description: 'Banheira com hidromassagem',
    icon: '💦',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZD0687B3KVE3H4XPEJ`,
    code: 'piscina_aquecida',
    name: 'Piscina Aquecida',
    description: 'Piscina com água aquecida',
    icon: '🏊',
    is_predefined: true,
    is_active: true,
  },

  // ===== SAÚDE & CLÍNICA =====
  {
    id: `${PREFIX}_01KCABRCZD7WH99D81YTGMTT7A`,
    code: 'atendimento_medico',
    name: 'Atendimento Médico',
    description: 'Médico responsável no local',
    icon: '👨‍⚕️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZD12VXQW16HWN5S9A9`,
    code: 'enfermagem',
    name: 'Equipe de Enfermagem',
    description: 'Enfermeiros disponíveis',
    icon: '👩‍⚕️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDE0V86AK8Q2SM97JK`,
    code: 'desfibrilador',
    name: 'Desfibrilador (DEA)',
    description: 'Desfibrilador externo automático disponível',
    icon: '❤️‍🩹',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZD774XCGCHS160XCAN`,
    code: 'primeiros_socorros',
    name: 'Kit de Primeiros Socorros',
    description: 'Equipamento de emergência disponível',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDHS12MGX5J8XMV6FN`,
    code: 'oximetro',
    name: 'Oxímetro',
    description: 'Medição de oxigênio disponível',
    icon: '📊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZD9F33J7YDT50BYBKY`,
    code: 'balanca_bioimpedancia',
    name: 'Balança de Bioimpedância',
    description: 'Avaliação de composição corporal',
    icon: '⚖️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDCFS9SS3XGDNGEA9X`,
    code: 'dermoscopia',
    name: 'Dermoscopia Digital',
    description: 'Análise digital da pele',
    icon: '🔍',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDD6C3WWK1M70YQ2QT`,
    code: 'tricoscopia',
    name: 'Tricoscopia',
    description: 'Análise do couro cabeludo',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },

  // ===== CERTIFICAÇÕES & QUALIDADE =====
  {
    id: `${PREFIX}_01KCABRCZD14H0QV3P5FPV6C25`,
    code: 'alvara_sanitario',
    name: 'Alvará Sanitário',
    description: 'Estabelecimento regularizado na vigilância',
    icon: '📜',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDVA94GS1KZCG33FTK`,
    code: 'iso_certificado',
    name: 'Certificação ISO',
    description: 'Processos certificados ISO',
    icon: '🏅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDYM55B1XKCGRE4HG7`,
    code: 'profissionais_certificados',
    name: 'Profissionais Certificados',
    description: 'Equipe com certificações reconhecidas',
    icon: '🎓',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDQ9XR8YKPZWD61GK8`,
    code: 'anvisa_aprovado',
    name: 'Produtos Aprovados ANVISA',
    description: 'Todos produtos regularizados na ANVISA',
    icon: '✅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDEWXGV0R4PM39WJEC`,
    code: 'seguro_responsabilidade',
    name: 'Seguro de Responsabilidade',
    description: 'Estabelecimento com seguro',
    icon: '🛡️',
    is_predefined: true,
    is_active: true,
  },

  // ===== AMBIENTE & DECORAÇÃO =====
  {
    id: `${PREFIX}_01KCABRCZDZ8YART3MYKGXP8VG`,
    code: 'ambiente_moderno',
    name: 'Ambiente Moderno',
    description: 'Decoração contemporânea e sofisticada',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDBKS27P8GFRGXQZ3Y`,
    code: 'ambiente_rustico',
    name: 'Ambiente Rústico',
    description: 'Decoração acolhedora e rústica',
    icon: '🪵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDTQ2YR648A2HWFT06`,
    code: 'ambiente_zen',
    name: 'Ambiente Zen',
    description: 'Atmosfera relaxante e tranquila',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDWGD8YA0RSQFSXRDF`,
    code: 'jardim_interno',
    name: 'Jardim Interno',
    description: 'Plantas e jardim no ambiente',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZD0MFCT2SEJAKK6AVR`,
    code: 'vista_panoramica',
    name: 'Vista Panorâmica',
    description: 'Vista privilegiada do local',
    icon: '🌆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDM6XRN11WJJWR5C1X`,
    code: 'iluminacao_natural',
    name: 'Iluminação Natural',
    description: 'Ambiente com luz natural abundante',
    icon: '☀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDB8JY4NF1YFSKBR5T`,
    code: 'varanda',
    name: 'Varanda/Terraço',
    description: 'Área externa disponível',
    icon: '🏞️',
    is_predefined: true,
    is_active: true,
  },

  // ===== IDIOMAS & COMUNICAÇÃO =====
  {
    id: `${PREFIX}_01KCABRCZD3HMM241EH7X559FK`,
    code: 'atendimento_ingles',
    name: 'Atendimento em Inglês',
    description: 'Profissionais fluentes em inglês',
    icon: '🇺🇸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDVSMX00Y9HCYFQNYH`,
    code: 'atendimento_espanhol',
    name: 'Atendimento em Espanhol',
    description: 'Profissionais fluentes em espanhol',
    icon: '🇪🇸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDBJT38SHE6B721TCC`,
    code: 'atendimento_libras',
    name: 'Atendimento em Libras',
    description: 'Profissionais que se comunicam em Libras',
    icon: '🤟',
    is_predefined: true,
    is_active: true,
  },

  // ===== SUSTENTABILIDADE =====
  {
    id: `${PREFIX}_01KCABRCZD1KMTYHB66KKQJ8WA`,
    code: 'energia_solar',
    name: 'Energia Solar',
    description: 'Uso de energia renovável',
    icon: '🌞',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDQXAPG0WD0YD1WAVE`,
    code: 'reciclagem',
    name: 'Programa de Reciclagem',
    description: 'Descarte consciente de materiais',
    icon: '♻️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDJVJYK8G12XGN5KAS`,
    code: 'sem_plastico',
    name: 'Livre de Plástico',
    description: 'Uso reduzido de plásticos descartáveis',
    icon: '🌍',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZDHHWFEFAKY2CFMD5Z`,
    code: 'economia_agua',
    name: 'Economia de Água',
    description: 'Práticas de uso consciente de água',
    icon: '💧',
    is_predefined: true,
    is_active: true,
  },

  // ===== TECNOLOGIA =====
  {
    id: `${PREFIX}_01KCABRCZDP3PA6XHPZHY0GN5W`,
    code: 'tomadas_usb',
    name: 'Tomadas USB',
    description: 'Portas USB para carregar dispositivos',
    icon: '🔌',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE2FWYG4X19WRPDYSB`,
    code: 'carregador_celular',
    name: 'Carregador de Celular',
    description: 'Carregadores disponíveis para clientes',
    icon: '🔋',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEJ10WFF9K0Y672CP6`,
    code: 'tablet_entretenimento',
    name: 'Tablet para Entretenimento',
    description: 'Tablets disponíveis durante procedimentos',
    icon: '📱',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE361BC3K6FDF91FR8`,
    code: 'netflix_disponivel',
    name: 'Netflix/Streaming',
    description: 'Acesso a plataformas de streaming',
    icon: '🎬',
    is_predefined: true,
    is_active: true,
  },

  // ===== SERVIÇOS ADICIONAIS =====
  {
    id: `${PREFIX}_01KCABRCZESX56SP5K2H0Q8JHF`,
    code: 'estacionamento_bicicleta',
    name: 'Bicicletário',
    description: 'Espaço para guardar bicicletas',
    icon: '🚲',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEK219325DV7K11V81`,
    code: 'guarda_volumes',
    name: 'Guarda-volumes',
    description: 'Armários para guardar pertences',
    icon: '🔐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE3XKN7WRFC84NZY3B`,
    code: 'servico_manobrista',
    name: 'Manobrista',
    description: 'Serviço de manobrista disponível',
    icon: '🚙',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEHBPP6S29HN7FDHBS`,
    code: 'transfer',
    name: 'Serviço de Transfer',
    description: 'Transporte de ida e volta disponível',
    icon: '🚐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEA6P0FZP292PPC8AH`,
    code: 'loja_produtos',
    name: 'Loja de Produtos',
    description: 'Venda de produtos profissionais',
    icon: '🛒',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEDYQNESVAD7X475G3`,
    code: 'consultoria_gratuita',
    name: 'Consultoria Gratuita',
    description: 'Primeira avaliação sem custo',
    icon: '💬',
    is_predefined: true,
    is_active: true,
  },

  // ===== EXCLUSIVIDADES =====
  {
    id: `${PREFIX}_01KCABRCZEMTWK3YRJ7DN5W9AP`,
    code: 'atendimento_exclusivo',
    name: 'Atendimento Exclusivo',
    description: 'Um cliente por vez no estabelecimento',
    icon: '👤',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEATHKGS56C2RJ77RV`,
    code: 'horario_marcado',
    name: 'Horário Marcado Pontual',
    description: 'Atendimento sempre no horário agendado',
    icon: '⏰',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEXJ52N6QXPZFCKEG1`,
    code: 'sem_espera',
    name: 'Sem Tempo de Espera',
    description: 'Atendimento imediato sem fila',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEPHV3BSEYJJWA138B`,
    code: 'atendimento_personalizado',
    name: 'Atendimento Personalizado',
    description: 'Serviço customizado para cada cliente',
    icon: '🎯',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEBZV1DZQNT3ZXNHF9`,
    code: 'concierge',
    name: 'Serviço de Concierge',
    description: 'Assistência pessoal para clientes',
    icon: '🛎️',
    is_predefined: true,
    is_active: true,
  },

  // ===== EVENTOS & GRUPOS =====
  {
    id: `${PREFIX}_01KCABRCZEF0CNC2WFK93B57EP`,
    code: 'day_spa',
    name: 'Day Spa',
    description: 'Pacotes de dia inteiro disponíveis',
    icon: '🧖',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZENWZ6G9QENB9QJ43D`,
    code: 'despedida_solteira',
    name: 'Despedida de Solteira',
    description: 'Pacotes para festas de despedida',
    icon: '💍',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEZQSEX4D5YK3HWZEV`,
    code: 'spa_noiva',
    name: 'Spa da Noiva',
    description: 'Pacote especial para noivas',
    icon: '👰',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEE4M3V05QE54J2NB8`,
    code: 'aniversario',
    name: 'Pacote Aniversário',
    description: 'Celebre seu aniversário conosco',
    icon: '🎂',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE80N44FKK9TWS4V6J`,
    code: 'atendimento_grupos',
    name: 'Atendimento para Grupos',
    description: 'Recebemos grupos e eventos',
    icon: '👥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEPD0GHPCWG7AF7T8N`,
    code: 'eventos_corporativos',
    name: 'Eventos Corporativos',
    description: 'Pacotes para empresas',
    icon: '🏢',
    is_predefined: true,
    is_active: true,
  },

  // ===== DIFERENCIAIS =====
  {
    id: `${PREFIX}_01KCABRCZE6CJHNFQGD6100WP7`,
    code: 'resultado_garantido',
    name: 'Resultado Garantido',
    description: 'Garantia de satisfação com o serviço',
    icon: '✔️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEJYGWH75B4ND7QPWT`,
    code: 'retoque_gratuito',
    name: 'Retoque Gratuito',
    description: 'Retoque sem custo em até 7 dias',
    icon: '🔄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZETAZZ3A190RGX1YVJ`,
    code: 'acompanhamento_pos',
    name: 'Acompanhamento Pós-procedimento',
    description: 'Suporte após o atendimento',
    icon: '📞',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE3TV3M7AZ2Z9EWQHN`,
    code: 'fotos_antes_depois',
    name: 'Fotos Antes e Depois',
    description: 'Registro fotográfico do resultado',
    icon: '📸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEDW0N9EBPKRHPJ0EH`,
    code: 'kit_home_care',
    name: 'Kit Home Care',
    description: 'Kit de cuidados para casa incluso',
    icon: '📦',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZEJ44RR20CZSV9HT6W`,
    code: 'brinde_aniversariante',
    name: 'Brinde para Aniversariantes',
    description: 'Presente especial no mês do aniversário',
    icon: '🎁',
    is_predefined: true,
    is_active: true,
  },

  // ===== COMODIDADES ESPECÍFICAS CLÍNICAS =====
  {
    id: `${PREFIX}_01KCABRCZEZPSAXN5QSA09RHMQ`,
    code: 'sala_recuperacao',
    name: 'Sala de Recuperação',
    description: 'Espaço para repouso pós-procedimento',
    icon: '🛏️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZE2Z67XT83ZFTXNTNM`,
    code: 'centro_cirurgico',
    name: 'Centro Cirúrgico',
    description: 'Centro cirúrgico equipado',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZERRWAWYSQ5FYEDXTF`,
    code: 'laboratorio_proprio',
    name: 'Laboratório Próprio',
    description: 'Exames realizados no local',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFTRBBV57VM6EENGHW`,
    code: 'farmacia_interna',
    name: 'Farmácia Interna',
    description: 'Medicamentos disponíveis no local',
    icon: '💊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFT3N5ZWJZHCZ3C1MG`,
    code: 'convenio_medico',
    name: 'Aceita Convênio Médico',
    description: 'Atendimento por planos de saúde',
    icon: '🏷️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFVET0T5ZR8F249331`,
    code: 'nota_fiscal',
    name: 'Emite Nota Fiscal',
    description: 'Nota fiscal para reembolso de convênios',
    icon: '🧾',
    is_predefined: true,
    is_active: true,
  },

  // ===== WELLNESS & BEM-ESTAR =====
  {
    id: `${PREFIX}_01KCABRCZF4TPV27A9FT9B089H`,
    code: 'meditacao_guiada',
    name: 'Meditação Guiada',
    description: 'Sessões de meditação disponíveis',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFTEK10YSXKHZ9QSQ8`,
    code: 'yoga',
    name: 'Aulas de Yoga',
    description: 'Yoga disponível no espaço',
    icon: '🧘‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZF0T5M2NS750FK3NM5`,
    code: 'pilates',
    name: 'Aulas de Pilates',
    description: 'Pilates disponível no espaço',
    icon: '🏋️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFG54MZRQ1D89MFBCZ`,
    code: 'sala_descanso',
    name: 'Sala de Descanso',
    description: 'Espaço para relaxamento entre procedimentos',
    icon: '😴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZF0JXWJR04D87R53HV`,
    code: 'area_relaxamento',
    name: 'Área de Relaxamento',
    description: 'Espaço zen para meditação e descanso',
    icon: '🕯️',
    is_predefined: true,
    is_active: true,
  },

  // ===== MAIS COMODIDADES =====
  {
    id: `${PREFIX}_01KCABRCZFRR1GYJR6737X2VKT`,
    code: 'acessorio_cabelo',
    name: 'Acessórios para Cabelo',
    description: 'Venda de acessórios e enfeites',
    icon: '💇',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFC399Q23WVBNGB11T`,
    code: 'cosmeticos_venda',
    name: 'Cosméticos à Venda',
    description: 'Loja de cosméticos no local',
    icon: '💄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZF715SHZ45J8436P4M`,
    code: 'joias_acessorios',
    name: 'Joias e Acessórios',
    description: 'Venda de joias e bijuterias',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFCXKN5BRHW82HDWES`,
    code: 'roupas_moda',
    name: 'Boutique de Moda',
    description: 'Roupas e moda disponíveis',
    icon: '👗',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZF0EHGGABDW3S023XB`,
    code: 'personal_shopper',
    name: 'Personal Shopper',
    description: 'Consultoria de compras disponível',
    icon: '🛍️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCABRCZFF3X0GA1RD5T3R8R9`,
    code: 'workshop',
    name: 'Workshops e Cursos',
    description: 'Cursos e workshops disponíveis',
    icon: '📚',
    is_predefined: true,
    is_active: true,
  },
];
