export interface SpecialtySeed {
  id: string;
  code: string;
  name: string;
  description: string;
  icon: string;
  is_predefined: boolean;
  is_active: boolean;
}

const PREFIX = 'spec';

export const SPECIALTY_SEEDS: SpecialtySeed[] = [
  {
    id: `${PREFIX}_01KCA8QEHZ0ZE6DHQ40RNR59BX`,
    code: 'cabeleireiro',
    name: 'Cabeleireiro(a)',
    description: 'Profissional especializado em cortes, coloração, tratamentos e penteados',
    icon: '✂️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ0PMV3MYG66TECC69N`,
    code: 'barbeiro',
    name: 'Barbeiro(a)',
    description: 'Especialista em cortes masculinos, barba e tratamentos capilares masculinos',
    icon: '💈',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ043KKWG862DW6NGB3`,
    code: 'colorista',
    name: 'Colorista',
    description: 'Especialista em coloração, mechas, luzes e técnicas de cor capilar',
    icon: '🎨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ0TDBT2B5EK2VSRTZ5`,
    code: 'tricologista',
    name: 'Tricologista',
    description: 'Especialista em saúde do couro cabeludo e tratamento de queda capilar',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ0YZNRWR0AWP1DTYFN`,
    code: 'hair_stylist',
    name: 'Hair Stylist',
    description: 'Profissional especializado em penteados, escovas e finalizações',
    icon: '💇',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ004Y00QZPBVZGGEY0`,
    code: 'trancista',
    name: 'Trancista',
    description: 'Especialista em tranças, box braids, twist e penteados afro',
    icon: '🪢',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ0Q5HA35M358YSBW86`,
    code: 'visagista',
    name: 'Visagista',
    description: 'Profissional que harmoniza o visual através de corte, cor e estilo',
    icon: '👤',
    is_predefined: true,
    is_active: true,
  },

  // ===== UNHAS =====
  {
    id: `${PREFIX}_01KCA8QEJ1SEZ49P0Y5SCR07R2`,
    code: 'manicure',
    name: 'Manicure',
    description: 'Profissional de cuidados com unhas das mãos',
    icon: '💅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1YAMXCFPEZBZN9JNQ`,
    code: 'pedicure',
    name: 'Pedicure',
    description: 'Profissional de cuidados com unhas dos pés',
    icon: '🦶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1CHCAKA97GA0WR87M`,
    code: 'nail_designer',
    name: 'Nail Designer',
    description: 'Especialista em unhas artísticas, nail art e decorações elaboradas',
    icon: '🎀',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1HGKA9ZH5D2JAVQ6G`,
    code: 'alongamento_unhas',
    name: 'Especialista em Alongamento de Unhas',
    description: 'Profissional de alongamento em gel, acrílico, fibra de vidro e polygel',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA FACIAL =====
  {
    id: `${PREFIX}_01KCA8QEJ1CV45K9P3CZCH6J06`,
    code: 'esteticista',
    name: 'Esteticista',
    description: 'Especialista em tratamentos faciais e corporais',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1K3HT1E0EWZRDKZNM`,
    code: 'esteticista_facial',
    name: 'Esteticista Facial',
    description: 'Especialista em limpeza de pele, hidratação e tratamentos faciais',
    icon: '🧴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1HQJW3506HQ6Z891K`,
    code: 'cosmetologa',
    name: 'Cosmetóloga',
    description: 'Profissional especializada em cosméticos e tratamentos de pele',
    icon: '🧪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ10XVB98Z6XJG21NK1`,
    code: 'dermopigmentador',
    name: 'Dermopigmentador(a)',
    description: 'Especialista em micropigmentação de sobrancelhas, lábios e olhos',
    icon: '🖌️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1NX3CSZ2R6G57EPBD`,
    code: 'microblading',
    name: 'Especialista em Microblading',
    description: 'Profissional de micropigmentação fio a fio para sobrancelhas',
    icon: '✏️',
    is_predefined: true,
    is_active: true,
  },

  // ===== SOBRANCELHAS E CÍLIOS =====
  {
    id: `${PREFIX}_01KCA8QEJ1JN42ZNF3TKT2KFB9`,
    code: 'designer_sobrancelhas',
    name: 'Designer de Sobrancelhas',
    description: 'Especialista em design, modelagem e tratamento de sobrancelhas',
    icon: '👁️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1KXY14TWVDKK7T2FA`,
    code: 'lash_designer',
    name: 'Lash Designer',
    description: 'Especialista em extensão, lifting e design de cílios',
    icon: '👁️‍🗨️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ16WWX5KDKY5PQ82WA`,
    code: 'brow_lamination',
    name: 'Especialista em Brow Lamination',
    description: 'Profissional de laminação e alisamento de sobrancelhas',
    icon: '〰️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1CE42B0AXD9TF8568`,
    code: 'lash_lifting',
    name: 'Especialista em Lash Lifting',
    description: 'Profissional de lifting e curvatura de cílios naturais',
    icon: '⬆️',
    is_predefined: true,
    is_active: true,
  },

  // ===== MAQUIAGEM =====
  {
    id: `${PREFIX}_01KCA8QEJ1S49XTR2SMB4S5GXM`,
    code: 'maquiador',
    name: 'Maquiador(a)',
    description: 'Profissional de maquiagem para diversos eventos e ocasiões',
    icon: '💄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ156B12MV2X17JTJCR`,
    code: 'maquiador_noivas',
    name: 'Maquiador(a) de Noivas',
    description: 'Especialista em maquiagem para noivas e casamentos',
    icon: '👰',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ1JT82YXB14CBJVX9W`,
    code: 'maquiador_artistico',
    name: 'Maquiador(a) Artístico',
    description: 'Especialista em maquiagem artística, editorial e efeitos especiais',
    icon: '🎭',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ152CW1H49570GJEFT`,
    code: 'consultor_imagem',
    name: 'Consultor(a) de Imagem',
    description: 'Profissional de consultoria de imagem pessoal e estilo',
    icon: '👔',
    is_predefined: true,
    is_active: true,
  },

  // ===== DEPILAÇÃO =====
  {
    id: `${PREFIX}_01KCA8QEJ1MGEWMJK6TWC8Y5X7`,
    code: 'depilador',
    name: 'Depilador(a)',
    description: 'Especialista em depilação com cera, linha e outros métodos',
    icon: '🌸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ20G09J58MW4QTT3JR`,
    code: 'depilacao_laser',
    name: 'Especialista em Depilação a Laser',
    description: 'Profissional de depilação definitiva com laser e luz pulsada',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2ZHY2MJ2X8Q3JAQ58`,
    code: 'depilacao_egipcia',
    name: 'Especialista em Depilação Egípcia',
    description: 'Profissional de depilação com linha (threading)',
    icon: '🧵',
    is_predefined: true,
    is_active: true,
  },

  // ===== MASSAGEM E BEM-ESTAR =====
  {
    id: `${PREFIX}_01KCA8QEJ25SVW6GNRT6FH7WQE`,
    code: 'massagista',
    name: 'Massoterapeuta',
    description: 'Profissional de massagens relaxantes e terapêuticas',
    icon: '💆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2Z89HG3CSB4KEHG8G`,
    code: 'massagista_relaxante',
    name: 'Massagista Relaxante',
    description: 'Especialista em massagens relaxantes e anti-stress',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2FDCC6ZD25G812KM5`,
    code: 'massagista_desportivo',
    name: 'Massagista Desportivo',
    description: 'Especialista em massagem para atletas e recuperação muscular',
    icon: '🏃',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ24CJFY88RP6GQH24B`,
    code: 'quick_massage',
    name: 'Especialista em Quick Massage',
    description: 'Profissional de massagens rápidas em cadeira',
    icon: '🪑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ26KABXTQV2J4GW0ER`,
    code: 'shiatsu',
    name: 'Terapeuta Shiatsu',
    description: 'Especialista em massagem japonesa shiatsu',
    icon: '🇯🇵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2KSEDDPG206T679KM`,
    code: 'thai_massage',
    name: 'Terapeuta Thai Massage',
    description: 'Especialista em massagem tailandesa tradicional',
    icon: '🇹🇭',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2P0VTHRQWAQDJ5C7Z`,
    code: 'ayurveda',
    name: 'Terapeuta Ayurveda',
    description: 'Especialista em massagem e tratamentos ayurvédicos',
    icon: '🕉️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ28293RCWMESMS8PYY`,
    code: 'drenagem_linfatica',
    name: 'Especialista em Drenagem Linfática',
    description: 'Profissional de drenagem linfática manual e mecânica',
    icon: '💧',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2MC7H75C6J5V5A85S`,
    code: 'reflexologista',
    name: 'Reflexologista',
    description: 'Especialista em reflexologia podal e das mãos',
    icon: '🦶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2NDVR6ED01DDZ53EC`,
    code: 'quiropraxista',
    name: 'Quiropraxista',
    description: 'Profissional de ajustes na coluna vertebral e articulações',
    icon: '🦴',
    is_predefined: true,
    is_active: true,
  },

  // ===== PODOLOGIA =====
  {
    id: `${PREFIX}_01KCA8QEJ2BTBHRDHNXAPCXPJC`,
    code: 'podologo',
    name: 'Podólogo(a)',
    description: 'Profissional de cuidados com os pés e tratamento de unhas',
    icon: '🦶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2DRKV4PPNMBZ9CQG8`,
    code: 'podologo_clinico',
    name: 'Podólogo(a) Clínico',
    description: 'Especialista em tratamento de patologias dos pés',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2SSK01XPZ4GFT24S5`,
    code: 'podologo_diabetico',
    name: 'Podólogo(a) para Pé Diabético',
    description: 'Especialista em cuidados com pés de pacientes diabéticos',
    icon: '💉',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2Q98351ABA84AWQC1`,
    code: 'podologo_esportivo',
    name: 'Podólogo(a) Esportivo',
    description: 'Especialista em tratamento de pés de atletas',
    icon: '⚽',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ26MMYD8CM651JQ85B`,
    code: 'podologo_geriatrico',
    name: 'Podólogo(a) Geriátrico',
    description: 'Especialista em cuidados com pés de idosos',
    icon: '👴',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA CORPORAL =====
  {
    id: `${PREFIX}_01KCA8QEJ291YTEXYZSGSC84BH`,
    code: 'esteticista_corporal',
    name: 'Esteticista Corporal',
    description: 'Especialista em tratamentos estéticos para o corpo',
    icon: '🌟',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ28K1EMJND0T4CK7N2`,
    code: 'bronzeamento',
    name: 'Especialista em Bronzeamento',
    description: 'Profissional de bronzeamento artificial e natural',
    icon: '☀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ2D1JY5FYYTJZKA6JE`,
    code: 'criolipolise',
    name: 'Especialista em Criolipólise',
    description: 'Profissional de tratamento de gordura localizada por congelamento',
    icon: '❄️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3EGHPVS8JS7K0HGJH`,
    code: 'radiofrequencia',
    name: 'Especialista em Radiofrequência',
    description: 'Profissional de tratamentos com radiofrequência para flacidez',
    icon: '📡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ31XG4D6EF7QRWSFMP`,
    code: 'ultrassom_estetico',
    name: 'Especialista em Ultrassom Estético',
    description: 'Profissional de tratamentos com ultrassom para gordura e celulite',
    icon: '🔊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ342RPY2M6XT0RTZW5`,
    code: 'carboxiterapia',
    name: 'Especialista em Carboxiterapia',
    description: 'Profissional de tratamentos com gás carbônico',
    icon: '💨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3R8KVV3W56H71T81A`,
    code: 'endermologia',
    name: 'Especialista em Endermologia',
    description: 'Profissional de tratamento de celulite e modelagem corporal',
    icon: '🔄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3NE37PNS52E4G3H7C`,
    code: 'lipocavitacao',
    name: 'Especialista em Lipocavitação',
    description: 'Profissional de tratamento não invasivo para gordura localizada',
    icon: '💫',
    is_predefined: true,
    is_active: true,
  },

  // ===== TERAPIAS ALTERNATIVAS =====
  {
    id: `${PREFIX}_01KCA8QEJ3T6VJFDC5SVFQ7P4T`,
    code: 'acupunturista',
    name: 'Acupunturista',
    description: 'Especialista em acupuntura e medicina tradicional chinesa',
    icon: '📍',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3S222G8179DVYDWJZ`,
    code: 'aromaterapia',
    name: 'Aromaterapeuta',
    description: 'Especialista em tratamentos com óleos essenciais',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ332GN89325HH851SF`,
    code: 'reiki',
    name: 'Terapeuta Reiki',
    description: 'Especialista em terapia energética Reiki',
    icon: '🙏',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3GC5VPG7NB0DTXD2Z`,
    code: 'cromoterapia',
    name: 'Cromaterapeuta',
    description: 'Especialista em terapia com cores',
    icon: '🌈',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3PCXAJ7HEP0Q1NAM7`,
    code: 'cristaloterapia',
    name: 'Cristaloterapeuta',
    description: 'Especialista em terapia com cristais e pedras',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ39X8SBBVEGSQB1776`,
    code: 'auriculoterapia',
    name: 'Auriculoterapeuta',
    description: 'Especialista em terapia auricular',
    icon: '👂',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3KDFSWVMVB9ABMMFB`,
    code: 'florais',
    name: 'Terapeuta Floral',
    description: 'Especialista em florais de Bach e outros sistemas florais',
    icon: '🌺',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3R4ZPM8EJ2NNK5Z91`,
    code: 'musicoterapia',
    name: 'Musicoterapeuta',
    description: 'Especialista em terapia através da música',
    icon: '🎵',
    is_predefined: true,
    is_active: true,
  },

  // ===== YOGA E MEDITAÇÃO =====
  {
    id: `${PREFIX}_01KCA8QEJ3MYTAWE8FM37SE1JY`,
    code: 'instrutor_yoga',
    name: 'Instrutor(a) de Yoga',
    description: 'Profissional de aulas de yoga e práticas meditativas',
    icon: '🧘‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3RHJ5G4YAP7411D5C`,
    code: 'instrutor_pilates',
    name: 'Instrutor(a) de Pilates',
    description: 'Profissional de aulas de pilates solo e aparelhos',
    icon: '🏋️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3QTDWESXTD2VEZ001`,
    code: 'meditacao',
    name: 'Instrutor(a) de Meditação',
    description: 'Especialista em técnicas de meditação e mindfulness',
    icon: '🕯️',
    is_predefined: true,
    is_active: true,
  },

  // ===== NUTRIÇÃO E SAÚDE =====
  {
    id: `${PREFIX}_01KCA8QEJ335GDV7RFZF9AFBWW`,
    code: 'nutricionista',
    name: 'Nutricionista',
    description: 'Profissional de nutrição e reeducação alimentar',
    icon: '🥗',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3QGSEWT47N9XT99W2`,
    code: 'nutricionista_esportivo',
    name: 'Nutricionista Esportivo',
    description: 'Especialista em nutrição para atletas e praticantes de esportes',
    icon: '🏅',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ37D336P48G05NCDKK`,
    code: 'nutricionista_estetico',
    name: 'Nutricionista Estético',
    description: 'Especialista em nutrição voltada para estética e beleza',
    icon: '🍎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3JARFPNQ68N1AC3N9`,
    code: 'naturopata',
    name: 'Naturopata',
    description: 'Profissional de medicina natural e tratamentos alternativos',
    icon: '🌱',
    is_predefined: true,
    is_active: true,
  },

  // ===== FISIOTERAPIA E OSTEOPATIA =====
  {
    id: `${PREFIX}_01KCA8QEJ31ZPP9YMHF4BGPR4T`,
    code: 'fisioterapeuta',
    name: 'Fisioterapeuta',
    description: 'Profissional de reabilitação física e funcional',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3HP014FXTQP66QG4T`,
    code: 'fisioterapeuta_dermatofuncional',
    name: 'Fisioterapeuta Dermatofuncional',
    description: 'Especialista em fisioterapia estética e dermatológica',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3VK7RH9R6VDG0FNDX`,
    code: 'osteopata',
    name: 'Osteopata',
    description: 'Especialista em osteopatia e tratamento manual',
    icon: '🦴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ31DX62Q99XEN7YSQ4`,
    code: 'rpg',
    name: 'Fisioterapeuta RPG',
    description: 'Especialista em Reeducação Postural Global',
    icon: '🧍',
    is_predefined: true,
    is_active: true,
  },

  // ===== BIOMEDICINA ESTÉTICA =====
  {
    id: `${PREFIX}_01KCA8QEJ3Z97TZZEPF9F1M4TQ`,
    code: 'biomedico_estetico',
    name: 'Biomédico(a) Estético',
    description: 'Especialista em procedimentos estéticos injetáveis e laser',
    icon: '💉',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ3RPCQ99B3SQNSAZRT`,
    code: 'harmonizacao_facial',
    name: 'Especialista em Harmonização Facial',
    description: 'Profissional de preenchimento, toxina botulínica e bioestimuladores',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ34HZQJHK2YZ84AF62`,
    code: 'toxina_botulinica',
    name: 'Especialista em Toxina Botulínica',
    description: 'Profissional de aplicação de botox',
    icon: '💫',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4XHDH3BW0JKQG7K44`,
    code: 'preenchimento',
    name: 'Especialista em Preenchimento',
    description: 'Profissional de preenchimento com ácido hialurônico',
    icon: '💋',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4KBG11XECGR4GYQTC`,
    code: 'bioestimuladores',
    name: 'Especialista em Bioestimuladores',
    description: 'Profissional de aplicação de bioestimuladores de colágeno',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ445CC03BTCC47SD55`,
    code: 'peeling',
    name: 'Especialista em Peeling',
    description: 'Profissional de peelings químicos e mecânicos',
    icon: '🧪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ476S1F2C4F6QXH0BZ`,
    code: 'microagulhamento',
    name: 'Especialista em Microagulhamento',
    description: 'Profissional de microagulhamento e drug delivery',
    icon: '📌',
    is_predefined: true,
    is_active: true,
  },

  // ===== SPA E RELAXAMENTO =====
  {
    id: `${PREFIX}_01KCA8QEJ4YFWT6N78DHKNR5BV`,
    code: 'terapeuta_spa',
    name: 'Terapeuta de Spa',
    description: 'Profissional de tratamentos e rituais de spa',
    icon: '🧖',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ463MRE7WBR5CQFTXE`,
    code: 'hidroterapia',
    name: 'Especialista em Hidroterapia',
    description: 'Profissional de tratamentos com água',
    icon: '🌊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4KFWEZ042HEN44SY5`,
    code: 'sauna_terapeuta',
    name: 'Terapeuta de Sauna',
    description: 'Especialista em tratamentos com sauna e banhos térmicos',
    icon: '🔥',
    is_predefined: true,
    is_active: true,
  },

  // ===== TERAPIAS CAPILARES AVANÇADAS =====
  {
    id: `${PREFIX}_01KCA8QEJ472H31AY9MJ43MXC5`,
    code: 'ozonioterapia_capilar',
    name: 'Especialista em Ozonioterapia Capilar',
    description: 'Profissional de tratamento capilar com ozônio',
    icon: '💨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4G5GZPZYFVHTD25RH`,
    code: 'botox_capilar',
    name: 'Especialista em Botox Capilar',
    description: 'Profissional de tratamentos de reconstrução capilar intensiva',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ43M3B9TRWZ4PTCSEW`,
    code: 'cauterizacao',
    name: 'Especialista em Cauterização Capilar',
    description: 'Profissional de selagem e reconstrução de fios danificados',
    icon: '🔥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ48BVSFBYJYS7E1WAQ`,
    code: 'escova_progressiva',
    name: 'Especialista em Escova Progressiva',
    description: 'Profissional de alisamento e redução de volume capilar',
    icon: '💇‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4QZG0E28VD0VANXHK`,
    code: 'permanente_afro',
    name: 'Especialista em Permanente Afro',
    description: 'Profissional de permanentes e tratamentos para cabelos crespos',
    icon: '🌀',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ49QYK2A9VSCJB94Q1`,
    code: 'mega_hair',
    name: 'Especialista em Mega Hair',
    description: 'Profissional de alongamento capilar e apliques',
    icon: '👩‍🦰',
    is_predefined: true,
    is_active: true,
  },

  // ===== TRATAMENTOS DERMATOLÓGICOS =====
  {
    id: `${PREFIX}_01KCA8QEJ480WS9J58R4BPGQ6C`,
    code: 'laser_dermatologico',
    name: 'Especialista em Laser Dermatológico',
    description: 'Profissional de tratamentos com laser para pele',
    icon: '💡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ46RK5N055ZF7MNJQM`,
    code: 'luz_pulsada',
    name: 'Especialista em Luz Pulsada',
    description: 'Profissional de tratamentos com luz pulsada intensa (IPL)',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4ZKJ4NNMYMHADHHHE`,
    code: 'led_terapia',
    name: 'Especialista em LED Terapia',
    description: 'Profissional de fototerapia com LED',
    icon: '🔴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ44XD7C8C8HWJVQAQE`,
    code: 'jato_plasma',
    name: 'Especialista em Jato de Plasma',
    description: 'Profissional de tratamentos com jato de plasma',
    icon: '✴️',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA ÍNTIMA =====
  {
    id: `${PREFIX}_01KCA8QEJ4ZCQJ3KBB4C3AP03T`,
    code: 'estetica_intima',
    name: 'Especialista em Estética Íntima',
    description: 'Profissional de tratamentos estéticos na região íntima',
    icon: '🌸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ472CQE575RESC8YA0`,
    code: 'clareamento_intimo',
    name: 'Especialista em Clareamento Íntimo',
    description: 'Profissional de clareamento de região íntima',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },

  // ===== TATUAGEM E PIERCING =====
  {
    id: `${PREFIX}_01KCA8QEJ4ENZZTZVMRXTV2SP7`,
    code: 'tatuador',
    name: 'Tatuador(a)',
    description: 'Profissional de tatuagem artística',
    icon: '🎨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4CJY9TMCDA6NCK4N1`,
    code: 'body_piercer',
    name: 'Body Piercer',
    description: 'Profissional de perfuração corporal',
    icon: '💎',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ47NC65FA1CQ47FKQR`,
    code: 'remocao_tatuagem',
    name: 'Especialista em Remoção de Tatuagem',
    description: 'Profissional de remoção a laser de tatuagens',
    icon: '🔆',
    is_predefined: true,
    is_active: true,
  },

  // ===== COACHING E PSICOLOGIA =====
  {
    id: `${PREFIX}_01KCA8QEJ443G0G7GJH2HY7T37`,
    code: 'psicologo',
    name: 'Psicólogo(a)',
    description: 'Profissional de saúde mental e bem-estar psicológico',
    icon: '🧠',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4G9NJYHD0MA5HQT8K`,
    code: 'life_coach',
    name: 'Life Coach',
    description: 'Profissional de coaching de vida e desenvolvimento pessoal',
    icon: '🎯',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ4BF4FTF93EJ20XA6X`,
    code: 'hipnoterapeuta',
    name: 'Hipnoterapeuta',
    description: 'Profissional de hipnoterapia clínica',
    icon: '🌀',
    is_predefined: true,
    is_active: true,
  },

  // ===== EDUCAÇÃO FÍSICA E PERSONAL =====
  {
    id: `${PREFIX}_01KCA8QEJ4N1F5ZJFSKH38RH62`,
    code: 'personal_trainer',
    name: 'Personal Trainer',
    description: 'Profissional de treinamento físico personalizado',
    icon: '💪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5E27W7VT2ZSERVP1A`,
    code: 'instrutor_funcional',
    name: 'Instrutor(a) Funcional',
    description: 'Profissional de treinamento funcional',
    icon: '🏋️‍♂️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5TDBBBG5JGBKR3ZS8`,
    code: 'instrutor_crossfit',
    name: 'Instrutor(a) de CrossFit',
    description: 'Profissional de treinamento CrossFit',
    icon: '🏆',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ503GJ5SRS50MGHMDJ`,
    code: 'instrutor_spinning',
    name: 'Instrutor(a) de Spinning',
    description: 'Profissional de aulas de spinning e ciclismo indoor',
    icon: '🚴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5TXB5NKVGFHX8HSH4`,
    code: 'instrutor_natacao',
    name: 'Instrutor(a) de Natação',
    description: 'Profissional de aulas de natação e hidroginástica',
    icon: '🏊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ52TKHP4HJ5XVDNSTB`,
    code: 'instrutor_danca',
    name: 'Instrutor(a) de Dança',
    description: 'Profissional de aulas de dança e coreografias',
    icon: '💃',
    is_predefined: true,
    is_active: true,
  },

  // ===== MEDICINA TRADICIONAL CHINESA =====
  {
    id: `${PREFIX}_01KCA8QEJ5PH649YAC8N4QDN1P`,
    code: 'moxaterapia',
    name: 'Especialista em Moxaterapia',
    description: 'Profissional de terapia com moxa (artemísia)',
    icon: '🔥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5NNB5D15FSWVG6NX9`,
    code: 'ventosaterapia',
    name: 'Especialista em Ventosaterapia',
    description: 'Profissional de terapia com ventosas',
    icon: '🔵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5DF4FWT03VFVDZRQ8`,
    code: 'tuina',
    name: 'Terapeuta Tui Na',
    description: 'Especialista em massagem terapêutica chinesa',
    icon: '🤲',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA MASCULINA =====
  {
    id: `${PREFIX}_01KCA8QEJ5TYJQ1T2ENG85EW8N`,
    code: 'estetica_masculina',
    name: 'Especialista em Estética Masculina',
    description: 'Profissional de tratamentos estéticos voltados para homens',
    icon: '🧔',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ56HV8HBMWS9AAR2S4`,
    code: 'tratamento_calvicie',
    name: 'Especialista em Tratamento de Calvície',
    description: 'Profissional de tratamentos para queda capilar masculina',
    icon: '👨‍🦲',
    is_predefined: true,
    is_active: true,
  },

  // ===== TERAPIA HOLÍSTICA =====
  {
    id: `${PREFIX}_01KCA8QEJ5PAQZMDAEJFMWMSXQ`,
    code: 'terapeuta_holistico',
    name: 'Terapeuta Holístico',
    description: 'Profissional de terapias integrativas e holísticas',
    icon: '🌐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5H2Q1B62VTWTNZ63Q`,
    code: 'constelacao_familiar',
    name: 'Constelador(a) Familiar',
    description: 'Profissional de constelação familiar sistêmica',
    icon: '👨‍👩‍👧‍👦',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5J4X6QJYM4EP0HKGA`,
    code: 'radiestesia',
    name: 'Radiestesista',
    description: 'Especialista em radiestesia e harmonização de ambientes',
    icon: '🔮',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5X55CHR806PYSF10C`,
    code: 'numerologia',
    name: 'Numerólogo(a)',
    description: 'Especialista em numerologia e mapa numerológico',
    icon: '🔢',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ5JN3MEG1JRC0NC9ZE`,
    code: 'tarologia',
    name: 'Tarólogo(a)',
    description: 'Especialista em leitura de tarô',
    icon: '🃏',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ588JABGGV04XB2VA9`,
    code: 'astrologia',
    name: 'Astrólogo(a)',
    description: 'Especialista em astrologia e mapa astral',
    icon: '⭐',
    is_predefined: true,
    is_active: true,
  },

  // ===== NOIVAS E EVENTOS =====
  {
    id: `${PREFIX}_01KCA8QEJ5ZN53SZF8Z78B454W`,
    code: 'produtor_noivas',
    name: 'Produtor(a) de Noivas',
    description: 'Profissional completo de produção para noivas',
    icon: '👰‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ6G30P6X8QMQH6FYWC`,
    code: 'produtor_eventos',
    name: 'Produtor(a) de Eventos',
    description: 'Profissional de produção de beleza para eventos',
    icon: '🎉',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ6DR7S05PNAQKSN6Q9`,
    code: 'produtor_formatura',
    name: 'Produtor(a) de Formatura',
    description: 'Especialista em produção de beleza para formaturas',
    icon: '🎓',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ6V30D7484TJPAF9J9`,
    code: 'produtor_debutante',
    name: 'Produtor(a) de Debutantes',
    description: 'Especialista em produção de beleza para 15 anos',
    icon: '🎀',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA INFANTIL =====
  {
    id: `${PREFIX}_01KCA8QEJ77GE4FC3TJBYDJ9DJ`,
    code: 'cabeleireiro_infantil',
    name: 'Cabeleireiro(a) Infantil',
    description: 'Especialista em cortes e penteados infantis',
    icon: '👧',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA8QEJ7AR8C2P09G104J6MY`,
    code: 'manicure_infantil',
    name: 'Manicure Infantil',
    description: 'Especialista em cuidados com unhas infantis',
    icon: '🧒',
    is_predefined: true,
    is_active: true,
  },

  // ===== NOVAS ESPECIALIDADES - CABELO =====
  {
    id: `${PREFIX}_01KCA9EHSSTYVMVPKX7T1J0X0B`,
    code: 'terapeuta_capilar',
    name: 'Terapeuta Capilar',
    description: 'Especialista em tratamentos capilares e saúde dos fios',
    icon: '💆‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSSE36YBSVM857T4YHS`,
    code: 'especialista_cabelos_cacheados',
    name: 'Especialista em Cabelos Cacheados',
    description: 'Profissional especializado em corte e tratamento de cabelos cacheados',
    icon: '🌀',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSSP7MJH3GRZKP121J0`,
    code: 'especialista_cabelos_crespos',
    name: 'Especialista em Cabelos Crespos',
    description: 'Profissional especializado em corte e tratamento de cabelos crespos',
    icon: '✊🏿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSS0VX0CF8G5JQVPT6G`,
    code: 'especialista_cabelos_lisos',
    name: 'Especialista em Cabelos Lisos',
    description: 'Profissional especializado em corte e tratamento de cabelos lisos',
    icon: '〰️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSSVSQEHYEFSX91Q8WR`,
    code: 'especialista_loiros',
    name: 'Especialista em Loiros',
    description: 'Profissional especializado em coloração e manutenção de cabelos loiros',
    icon: '👱‍♀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST1TQJ40CBFQSFQXW2`,
    code: 'especialista_platinados',
    name: 'Especialista em Platinados',
    description: 'Profissional especializado em descoloração e cabelos platinados',
    icon: '⚪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST3MTJRV7C1EAYNDBA`,
    code: 'especialista_cabelos_afro',
    name: 'Especialista em Cabelos Afro',
    description: 'Profissional especializado em cabelos afro e texturas naturais',
    icon: '🖤',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTQ5EPZBY2FEGMMHV3`,
    code: 'especialista_protese_capilar',
    name: 'Especialista em Prótese Capilar',
    description: 'Profissional de aplicação e manutenção de próteses capilares',
    icon: '🧢',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST1KM7V6T7DYF4VA03`,
    code: 'especialista_perucas',
    name: 'Especialista em Perucas',
    description: 'Profissional de confecção, aplicação e manutenção de perucas',
    icon: '👩‍🦱',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST12P7J72967QWBZ7J`,
    code: 'especialista_alisamentos',
    name: 'Especialista em Alisamentos',
    description: 'Profissional de técnicas de alisamento capilar',
    icon: '📏',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTWAJ1P29RZVYJ3SGD`,
    code: 'especialista_cortes_masculinos',
    name: 'Especialista em Cortes Masculinos',
    description: 'Profissional especializado em cortes de cabelo masculino',
    icon: '👨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTHH8T6QGY91Y47B8N`,
    code: 'especialista_cortes_femininos',
    name: 'Especialista em Cortes Femininos',
    description: 'Profissional especializado em cortes de cabelo feminino',
    icon: '👩',
    is_predefined: true,
    is_active: true,
  },

  // ===== BARBA & ESTÉTICA MASCULINA =====
  {
    id: `${PREFIX}_01KCA9EHST6VAQ27SACCCZFSD7`,
    code: 'barbearia_tradicional',
    name: 'Barbearia Tradicional',
    description: 'Serviços clássicos de barbearia com técnicas tradicionais',
    icon: '💈',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTAYT0PN8W3V6DXXRR`,
    code: 'barbearia_premium',
    name: 'Barbearia Premium',
    description: 'Serviços de barbearia de alto padrão com experiência diferenciada',
    icon: '👑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTY0VARPHWVY83P8P2`,
    code: 'terapia_barba',
    name: 'Terapeuta de Barba',
    description: 'Especialista em tratamentos e cuidados com a barba',
    icon: '🧴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTG8DS853YYXXX80B3`,
    code: 'designer_barba',
    name: 'Designer de Barba',
    description: 'Especialista em modelagem e design de barba',
    icon: '✂️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTWDHYNMXN19EEYK8G`,
    code: 'visagista_masculino',
    name: 'Especialista em Visagismo Masculino',
    description: 'Profissional de harmonização da imagem masculina',
    icon: '👔',
    is_predefined: true,
    is_active: true,
  },

  // ===== UNHAS ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSTXXYZM0WGR5C3M4GB`,
    code: 'nail_artist',
    name: 'Nail Artist',
    description: 'Artista especializado em criações únicas e personalizadas em unhas',
    icon: '🎨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTYP2NRS8GHHBAFYB8`,
    code: 'especialista_unhas_gel',
    name: 'Especialista em Unhas em Gel',
    description: 'Profissional especializado em técnicas de unhas em gel',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST0PZCS64C4PG53RSZ`,
    code: 'especialista_unhas_acrilicas',
    name: 'Especialista em Unhas Acrílicas',
    description: 'Profissional especializado em unhas de acrílico',
    icon: '💫',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTGAR1RNRT3V4BGM5M`,
    code: 'especialista_unhas_fibra',
    name: 'Especialista em Unhas de Fibra',
    description: 'Profissional especializado em unhas de fibra de vidro',
    icon: '🔮',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTVG4D88RPFSZEG5W8`,
    code: 'podologo_estetico',
    name: 'Podólogo(a) Estético',
    description: 'Especialista em tratamentos estéticos para os pés',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },

  // ===== SOBRANCELHAS & CÍLIOS ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSTX67TKX4XJM2QR7VW`,
    code: 'especialista_sobrancelhas',
    name: 'Especialista em Sobrancelhas',
    description: 'Profissional completo em tratamentos e técnicas para sobrancelhas',
    icon: '🖌️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTAJVCRG8003SH9PYF`,
    code: 'lash_artist',
    name: 'Lash Artist',
    description: 'Artista especializado em técnicas avançadas de cílios',
    icon: '✨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHST2327TMRSWCK5D8G4`,
    code: 'especialista_cilios',
    name: 'Especialista em Cílios',
    description: 'Profissional completo em extensão, lifting e tratamento de cílios',
    icon: '👀',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTQ8YYNNEMRSTW2Y8D`,
    code: 'micropigmentador',
    name: 'Micropigmentador(a)',
    description: 'Profissional de micropigmentação de sobrancelhas, lábios e olhos',
    icon: '🖌️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTXZHA3RXCKF45ZV6K`,
    code: 'especialista_micropigmentacao',
    name: 'Especialista em Micropigmentação',
    description: 'Profissional de técnicas avançadas de micropigmentação',
    icon: '💉',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTE0NKYQP2QDSN1EDS`,
    code: 'maquiagem_definitiva',
    name: 'Especialista em Maquiagem Definitiva',
    description: 'Profissional de maquiagem definitiva e semi-permanente',
    icon: '💄',
    is_predefined: true,
    is_active: true,
  },

  // ===== MAQUIAGEM ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSTQ3JZ8H32RDYWKK9Y`,
    code: 'maquiador_profissional',
    name: 'Maquiador(a) Profissional',
    description: 'Profissional certificado em técnicas avançadas de maquiagem',
    icon: '🎨',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTTTBYQ0F5AQE97VDW`,
    code: 'maquiador_social',
    name: 'Maquiador(a) Social',
    description: 'Especialista em maquiagem para eventos sociais',
    icon: '🌟',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSTV0GFFPXFHSM5388F`,
    code: 'personal_stylist',
    name: 'Personal Stylist',
    description: 'Profissional de consultoria de moda e estilo pessoal',
    icon: '👗',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA FACIAL ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSTHEKDMY8SNNT5KWJ3`,
    code: 'especialista_rejuvenescimento',
    name: 'Especialista em Rejuvenescimento Facial',
    description: 'Profissional de tratamentos anti-envelhecimento e rejuvenescimento',
    icon: '🌟',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV23AQADZTMSJDWT95`,
    code: 'especialista_acne',
    name: 'Especialista em Acne',
    description: 'Profissional especializado no tratamento de acne e pele oleosa',
    icon: '🔵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVZ0PCQNM6ME7VZS09`,
    code: 'especialista_manchas',
    name: 'Especialista em Manchas',
    description: 'Profissional de tratamento de manchas e hiperpigmentação',
    icon: '🎯',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVE1PC4KVM79YGV0D7`,
    code: 'especialista_melasma',
    name: 'Especialista em Melasma',
    description: 'Profissional especializado em tratamento de melasma',
    icon: '☀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVD1QZJJH3CF01BMM2`,
    code: 'especialista_anti_idade',
    name: 'Especialista em Estética Anti-idade',
    description: 'Profissional de tratamentos preventivos e corretivos do envelhecimento',
    icon: '⏰',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVTW415X3H7B4JEJE6`,
    code: 'especialista_tecnologias_faciais',
    name: 'Especialista em Tecnologias Estéticas Faciais',
    description: 'Profissional de equipamentos e tecnologias para tratamentos faciais',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA CORPORAL ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSVWRJ2BD4SMTNCT6VY`,
    code: 'especialista_gordura_localizada',
    name: 'Especialista em Gordura Localizada',
    description: 'Profissional de tratamentos para redução de gordura localizada',
    icon: '📍',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV87VV28VWS84SCXFA`,
    code: 'especialista_celulite',
    name: 'Especialista em Celulite',
    description: 'Profissional de tratamentos para celulite e fibro edema gelóide',
    icon: '🔄',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV022NY1DD7CM6856F`,
    code: 'especialista_flacidez',
    name: 'Especialista em Flacidez',
    description: 'Profissional de tratamentos para flacidez de pele e muscular',
    icon: '💪',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV77KDM99RW4B9DEQP`,
    code: 'especialista_contorno_corporal',
    name: 'Especialista em Contorno Corporal',
    description: 'Profissional de tratamentos para modelagem e contorno do corpo',
    icon: '🎯',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV1CPTHSK6TD2QM1TY`,
    code: 'especialista_pre_pos_operatorio',
    name: 'Especialista em Estética Pré e Pós-operatória',
    description: 'Profissional de tratamentos antes e após cirurgias estéticas',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVH5H83P70FRJAZ49H`,
    code: 'especialista_tecnologias_corporais',
    name: 'Especialista em Tecnologias Estéticas Corporais',
    description: 'Profissional de equipamentos e tecnologias para tratamentos corporais',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA ÍNTIMA ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSV616WK9177H473RBV`,
    code: 'estetica_intima_feminina',
    name: 'Estética Íntima Feminina',
    description: 'Especialista em tratamentos estéticos íntimos femininos',
    icon: '🌷',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV459WHG7BJ6RZWMNN`,
    code: 'estetica_intima_masculina',
    name: 'Estética Íntima Masculina',
    description: 'Especialista em tratamentos estéticos íntimos masculinos',
    icon: '🔵',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVW3QZW6KJVQ5JCATA`,
    code: 'saude_intima_estetica',
    name: 'Especialista em Saúde Íntima Estética',
    description: 'Profissional de saúde e estética íntima integrada',
    icon: '💜',
    is_predefined: true,
    is_active: true,
  },

  // ===== ESTÉTICA AVANÇADA & CLÍNICA =====
  {
    id: `${PREFIX}_01KCA9EHSVKXQCXB45Q2E6DA6W`,
    code: 'estetica_avancada',
    name: 'Estética Avançada',
    description: 'Profissional de procedimentos estéticos avançados',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVQBHJ1CMK05QCFGPD`,
    code: 'estetica_clinica',
    name: 'Estética Clínica',
    description: 'Profissional de estética em ambiente clínico',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV84PK142QEQ1Y5EPE`,
    code: 'estetica_integrativa',
    name: 'Estética Integrativa',
    description: 'Profissional de estética com abordagem integrativa',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV01N5ZFCQGXX9J1EW`,
    code: 'farmaceutico_esteta',
    name: 'Farmacêutico(a) Esteta',
    description: 'Farmacêutico especialista em procedimentos estéticos',
    icon: '💊',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVC711EQT247YY58VQ`,
    code: 'enfermeiro_esteta',
    name: 'Enfermeiro(a) Esteta',
    description: 'Enfermeiro especialista em procedimentos estéticos',
    icon: '👩‍⚕️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV1CVHN8G5RBVH78GT`,
    code: 'medico_esteta',
    name: 'Médico(a) Esteta',
    description: 'Médico especialista em medicina estética',
    icon: '👨‍⚕️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVS1ANWJRAYNP140DJ`,
    code: 'dermatologia_estetica',
    name: 'Dermatologia Estética',
    description: 'Dermatologista com foco em procedimentos estéticos',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },

  // ===== SAÚDE (CLÍNICA & ESPECIALIDADES MÉDICAS) =====
  {
    id: `${PREFIX}_01KCA9EHSV4X8MYQ5SKKPYHGCX`,
    code: 'clinica_medica',
    name: 'Clínica Médica',
    description: 'Médico clínico geral para atendimento de saúde',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVF891135SXKZZA337`,
    code: 'dermatologia',
    name: 'Dermatologia',
    description: 'Médico especialista em doenças da pele, cabelos e unhas',
    icon: '🔬',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVX225PE2YXYXWC79X`,
    code: 'ginecologia',
    name: 'Ginecologia',
    description: 'Médico especialista em saúde da mulher',
    icon: '🩺',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSV1K8N2AM322HCYDRG`,
    code: 'urologia',
    name: 'Urologia',
    description: 'Médico especialista em sistema urinário e reprodutor masculino',
    icon: '🩺',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVV3R4AM2D7FPR70WS`,
    code: 'endocrinologia',
    name: 'Endocrinologia',
    description: 'Médico especialista em hormônios e metabolismo',
    icon: '⚗️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSVEDDQ57WTZKWK9VFT`,
    code: 'cardiologia',
    name: 'Cardiologia',
    description: 'Médico especialista em coração e sistema cardiovascular',
    icon: '❤️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW5GD6SV19DZ4VVSPC`,
    code: 'ortopedia',
    name: 'Ortopedia',
    description: 'Médico especialista em ossos, músculos e articulações',
    icon: '🦴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW5TP6T29QA4PBZAV4`,
    code: 'pediatria',
    name: 'Pediatria',
    description: 'Médico especialista em saúde de crianças e adolescentes',
    icon: '👶',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW4RPJ9N9K6A9BZWA8`,
    code: 'neurologia',
    name: 'Neurologia',
    description: 'Médico especialista em sistema nervoso',
    icon: '🧠',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW654VWAGQDQ0GQYF1`,
    code: 'psiquiatria',
    name: 'Psiquiatria',
    description: 'Médico especialista em saúde mental e transtornos psiquiátricos',
    icon: '🧠',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWSCMR97R696HXWVH4`,
    code: 'reumatologia',
    name: 'Reumatologia',
    description: 'Médico especialista em doenças reumáticas e autoimunes',
    icon: '🦴',
    is_predefined: true,
    is_active: true,
  },

  // ===== SAÚDE MENTAL & EMOCIONAL ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSWA0BXTPPMHRM1YNQJ`,
    code: 'psicologo_clinico',
    name: 'Psicólogo(a) Clínico',
    description: 'Psicólogo especializado em atendimento clínico',
    icon: '💭',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW0JAD9FS6V6K62ASQ`,
    code: 'psicanalise',
    name: 'Psicanalista',
    description: 'Profissional de psicanálise e análise do inconsciente',
    icon: '🛋️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWNYHDKTWGTG4J2TXY`,
    code: 'terapia_individual',
    name: 'Terapeuta Individual',
    description: 'Profissional de terapia psicológica individual',
    icon: '👤',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWF6WSEC5V4W0N2MY4`,
    code: 'terapia_casal',
    name: 'Terapeuta de Casal',
    description: 'Profissional de terapia para casais e relacionamentos',
    icon: '💑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWFVR5KP0ZV7CGAXDJ`,
    code: 'terapia_familiar',
    name: 'Terapeuta Familiar',
    description: 'Profissional de terapia familiar sistêmica',
    icon: '👨‍👩‍👧‍👦',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWF0JBB2XFGEHHJ0A1`,
    code: 'terapia_comportamental',
    name: 'Terapeuta Comportamental',
    description: 'Profissional de terapia cognitivo-comportamental',
    icon: '🎯',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWS8F0MDXNNC52MYG4`,
    code: 'terapia_integrativa',
    name: 'Terapeuta Integrativo',
    description: 'Profissional de terapia integrativa e abordagens múltiplas',
    icon: '🌈',
    is_predefined: true,
    is_active: true,
  },

  // ===== FISIOTERAPIA ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSWCMPTMPN5PASFVJND`,
    code: 'fisioterapia_ortopedica',
    name: 'Fisioterapeuta Ortopédico',
    description: 'Especialista em reabilitação de lesões ortopédicas',
    icon: '🦴',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWARVREYEHB116WQR2`,
    code: 'fisioterapia_esportiva',
    name: 'Fisioterapeuta Esportivo',
    description: 'Especialista em reabilitação de atletas e esportistas',
    icon: '🏃',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWJE10AS3DP686J9E6`,
    code: 'fisioterapia_respiratoria',
    name: 'Fisioterapeuta Respiratório',
    description: 'Especialista em reabilitação respiratória e pulmonar',
    icon: '💨',
    is_predefined: true,
    is_active: true,
  },

  // ===== NUTRIÇÃO ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSWZ5TM9Q466ARW4MDA`,
    code: 'nutricionista_clinico',
    name: 'Nutricionista Clínico',
    description: 'Especialista em nutrição clínica e terapêutica',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW10S620QYXQTCBEC8`,
    code: 'nutricionista_funcional',
    name: 'Nutricionista Funcional',
    description: 'Especialista em nutrição funcional e personalizada',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW9WJDSAV2WGSRPNZ1`,
    code: 'nutricionista_integrativo',
    name: 'Nutricionista Integrativo',
    description: 'Especialista em nutrição com abordagem integrativa',
    icon: '🌱',
    is_predefined: true,
    is_active: true,
  },

  // ===== BEM-ESTAR ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSW8BYWG0ZJVTNQCX7E`,
    code: 'terapeuta_corporal',
    name: 'Terapeuta Corporal',
    description: 'Profissional de terapias corporais e consciência do corpo',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWWCM8A98V8SJJRXBW`,
    code: 'terapias_integrativas',
    name: 'Terapeuta Integrativo',
    description: 'Profissional de terapias integrativas e complementares',
    icon: '🌈',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWKRSJ261WP629HK4C`,
    code: 'terapias_alternativas',
    name: 'Terapeuta Alternativo',
    description: 'Profissional de terapias alternativas e naturais',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWM0KVHDSAQQMVKED8`,
    code: 'terapias_energeticas',
    name: 'Terapeuta Energético',
    description: 'Profissional de terapias energéticas e equilíbrio vital',
    icon: '⚡',
    is_predefined: true,
    is_active: true,
  },

  // ===== CORPO & MENTE ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSWYVEHKQHECGX68RJS`,
    code: 'pilates_clinico',
    name: 'Instrutor(a) de Pilates Clínico',
    description: 'Profissional de pilates com foco em reabilitação',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW5DH7K1R09XNX6NGF`,
    code: 'pilates_solo',
    name: 'Instrutor(a) de Pilates Solo',
    description: 'Profissional de pilates mat (solo)',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWWYV6X1G3HBF36JEY`,
    code: 'instrutor_alongamento',
    name: 'Instrutor(a) de Alongamento',
    description: 'Profissional de aulas de alongamento e flexibilidade',
    icon: '🤸',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSWXTZYZ333213XQXB8`,
    code: 'mindfulness',
    name: 'Instrutor(a) de Mindfulness',
    description: 'Especialista em técnicas de atenção plena',
    icon: '🧠',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW37CG35T8RZ0RED9B`,
    code: 'tai_chi_chuan',
    name: 'Instrutor(a) de Tai Chi Chuan',
    description: 'Profissional de tai chi chuan e artes internas',
    icon: '☯️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSW1QJE2EKG080NKKWN`,
    code: 'lian_gong',
    name: 'Instrutor(a) de Lian Gong',
    description: 'Profissional de lian gong e ginástica chinesa',
    icon: '🇨🇳',
    is_predefined: true,
    is_active: true,
  },

  // ===== SPA ADICIONAIS =====
  {
    id: `${PREFIX}_01KCA9EHSX4HGTGZ7T3S8SSK8H`,
    code: 'spa_urbano',
    name: 'Spa Urbano',
    description: 'Estabelecimento de spa em ambiente urbano',
    icon: '🏙️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXNNMP9AJ49TXRK9AC`,
    code: 'spa_terapeutico',
    name: 'Spa Terapêutico',
    description: 'Spa com foco em tratamentos terapêuticos',
    icon: '🏥',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXXQJ31A89SPJTX8S6`,
    code: 'day_spa',
    name: 'Day Spa',
    description: 'Spa para experiências de um dia',
    icon: '☀️',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXBE2JF8TF7JCGA1GV`,
    code: 'wellness_center',
    name: 'Wellness Center',
    description: 'Centro integrado de bem-estar e saúde',
    icon: '🌟',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSX7BDC8GPEX1E33F89`,
    code: 'centro_bem_estar',
    name: 'Centro de Bem-estar',
    description: 'Espaço dedicado ao bem-estar integral',
    icon: '🧘',
    is_predefined: true,
    is_active: true,
  },

  // ===== CATEGORIAS TRANSVERSAIS =====
  {
    id: `${PREFIX}_01KCA9EHSX1THB0AN2W110P4VF`,
    code: 'estetica_feminina',
    name: 'Estética Feminina',
    description: 'Tratamentos estéticos voltados para o público feminino',
    icon: '👩',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXBSTZ15GCPDGY6QPW`,
    code: 'estetica_unissex',
    name: 'Estética Unissex',
    description: 'Tratamentos estéticos para todos os públicos',
    icon: '🌐',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXBBVMZWBQS19SFVGZ`,
    code: 'saude_integrativa',
    name: 'Saúde Integrativa',
    description: 'Abordagem integrativa de saúde e bem-estar',
    icon: '🌿',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXE1BVDEV5M9BEGAD9`,
    code: 'bem_estar_corporativo',
    name: 'Bem-estar Corporativo',
    description: 'Serviços de bem-estar para empresas e colaboradores',
    icon: '🏢',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXRVW0V9BWTREJM7K8`,
    code: 'beleza_premium',
    name: 'Beleza Premium',
    description: 'Serviços de beleza de alto padrão',
    icon: '👑',
    is_predefined: true,
    is_active: true,
  },
  {
    id: `${PREFIX}_01KCA9EHSXBN8XQE6W760DRDNE`,
    code: 'beleza_popular',
    name: 'Beleza Popular',
    description: 'Serviços de beleza acessíveis',
    icon: '💅',
    is_predefined: true,
    is_active: true,
  },
];
